### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by RedDeadDepresso** [n0k0m3/PerseusCI#7]
Hi, I've followed the README instructions and successfully generated the APK. However, after installing the APK and granting storage permission, it shows me a black screen.

I've attempted to install it on both my phone and Bluestacks, but the problem remains the same. 

Does Peaseus still work or it has been patched? If not, do I need to perform additional steps? I'm not familiar with android development.
![Screenshot_2023-11-08-09-10-27-089_com YoStarEN AzurLane](https://github.com/n0k0m3/PerseusCI/assets/94017243/bec149e8-7991-4729-b205-563066dfa8af)

**Comment by n0k0m3** [comment]
Need obb
